### ISSUE TITLE
Issue regarding search width in staged expansion of iQAN paper

### ISSUE THREAD

**Issue by gloriallluo** [johnpzh/iQAN_AE#1]
Dear author,

While reading your iQAN paper, I noticed that in the section on Staged Expansion, it was mentioned that the search width increases gradually with the number of search steps until it reaches a limit. I would like to adjust and test this setting, but I am not sure where in the code I should make the necessary changes.

Could you please provide me with some rough guidance on where I should look in the code to find this setting? Thank you!

**Comment by johnpzh** [comment]
Hi @gloriallluo . Thank you for being so interested in the project!

In the previous version, Staged Expansion can be found in another [repo](https://github.com/johnpzh/parallel_ANNS/blob/2116d7bf9207fc62c9a11b1919212506cc5a6447/core/Searching.202011241651.scale_m_pure.cpp#L4454). The value of `M` is the expansion width, and it is doubled in every iteration by `M <<= 1`.

In the last version, Staged Expansion is divided into two phases, a serial phase and a parallel phase. The serial phase can be tuned by the value of [`seq_iter_bound`](https://github.com/johnpzh/iQAN_AE/blob/da7359439ffa94909f243dd3df6be71b76ce1e35/core/Searching.202102022027.PSS_v5.dist_thresh.profiling.cpp#L1315).

Hope this would be helpful.

**Comment by gloriallluo** [comment]
Thank you for your timely response! That's really helpful.
