### ISSUE TITLE
Inquiry Regarding Inter-Query Parallelism Code in iQAN Paper

### ISSUE THREAD

**Issue by gloriallluo** [johnpzh/iQAN_AE#3]
Dear Author,

I observed in your iQAN paper that you conducted experiments on inter-query parallelism (as shown in Figure 17). While exploring the inter-query parallelism code in [parallel_ANNS](https://github.com/johnpzh/parallel_ANNS), I came across multiple iterations of this code. Could you please specify which version you employed for your final evaluation?

**Comment by johnpzh** [comment]
Dear @gloriallluo ,

Thank you so much for your interest in this work. Sorry for the late response. For the inter-query parallelism code, I think I used [app/PSS_v5_multi_queries.cpp](https://github.com/johnpzh/parallel_ANNS/blob/master/app/PSS_v5_multi_queries.cpp) and [app/PSS_v5_multi_queries_LG.cpp](https://github.com/johnpzh/parallel_ANNS/blob/master/app/PSS_v5_multi_queries_LG.cpp) for the final results.

**Comment by gloriallluo** [comment]
Thank you very much! @johnpzh
